# This is a YAML-formatted file.

replicaCount:
  gateway: 2
  cacher: 1
  builder: 1
  balloonA10: 0
  balloonA100: 0
  balloonCpu: 0
  balloonT4: 0

tag: 579319016a0d1ce7eaded5148c0059b2a1c86e41
context: production
image:
  gatewayRepository: 692474966980.dkr.ecr.us-west-2.amazonaws.com/llm-engine
  builderRepository: 692474966980.dkr.ecr.us-west-2.amazonaws.com/llm-engine
  cacherRepository: 692474966980.dkr.ecr.us-west-2.amazonaws.com/llm-engine
  forwarderRepository: 692474966980.dkr.ecr.us-west-2.amazonaws.com/llm-engine
  pullPolicy: Always

secrets:
  kubernetesDatabaseSecretName: ml-infra-pg

service:
  type: ClusterIP
  port: 80

virtualservice:
  enabled: true
  annotations: { }
  hostDomains:
    - egp-test.scale.com
  gateways:
    - default/internal-gateway

destinationrule:
  enabled: true
  annotations: { }

autoscaling:
  horizontal:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetConcurrency: 50
  vertical:
    enabled: false
#    minAllowed:
#      cpu: 100m
#      memory: 128Mi
#    maxAllowed:
#      cpu: 10
#      memory: 8Gi
#    updateMode: Initial # Auto disrupts the service (https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#quick-start)
  prewarming:
    enabled: false

resources:
  requests:
    cpu: 2

nodeSelector: { }

tolerations: [ ]

affinity: { }

config:
  values:
    infra:
      k8s_cluster_name: main_cluster
      dns_host_domain: egp-test.scale.com
      default_region: us-west-2
      ml_account_id: "692474966980"
      docker_repo_prefix: "692474966980.dkr.ecr.us-west-2.amazonaws.com"
      redis_host: spellbook-prod-cache-001.nu2e0g.0001.usw2.cache.amazonaws.com
      s3_bucket: "scale-ml-egp-test"
    llm_engine:
      model_primitive_host: none

      # Endpoint config
      # K8s namespace the endpoints will be created in
      endpoint_namespace: llm-engine

      # Asynchronous endpoints
      sqs_profile: default
      sqs_queue_policy_template: >
        {
          "Version": "2012-10-17",
          "Id": "__default_policy_ID",
          "Statement": [
            {
              "Sid": "__owner_statement",
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::985572151633:root"
              },
              "Action": "sqs:*",
              "Resource": "arn:aws:sqs:us-west-2:985572151633:${queue_name}"
            },
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::985572151633:role/k8s-main-llm-engine"
              },
              "Action": "sqs:*",
              "Resource": "arn:aws:sqs:us-west-2:985572151633:${queue_name}"
            }
          ]
        }

      sqs_queue_tag_template: >
        {
          "Spellbook-Serve-Endpoint-Id": "${endpoint_id}",
          "Spellbook-Serve-Endpoint-Name": "${endpoint_name}",
          "Spellbook-Serve-Endpoint-Created-By": "${endpoint_created_by}"
        }

      # Billing
      cache_redis_url: redis://spellbook-prod-cache-001.nu2e0g.0001.usw2.cache.amazonaws.com:6379/15

# Service Account
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::985572151633:role/k8s-main-llm-engine
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
  namespaces: []

aws:
  configMap:
    name: default-config
    create: true
  profileName: default

triton:
  image:
    repository: 692474966980.dkr.ecr.us-west-2.amazonaws.com/std-ml-srv
    tag: e83eccbc8959f90ebbe4bda618b61ec6ee2d8394-triton

serviceTemplate:
  securityContext:
    capabilities:
      drop:
        - all
  mountInfraConfig: true

imageCache:
  devices:
    - name: cpu
      nodeSelector:
        cpu-only: "true"
    - name: a10
      nodeSelector:
        k8s.amazonaws.com/accelerator: nvidia-ampere-a10
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
    - name: a100
      nodeSelector:
        k8s.amazonaws.com/accelerator: nvidia-ampere-a100
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
    - name: t4
      nodeSelector:
        k8s.amazonaws.com/accelerator: nvidia-tesla-t4
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"

celeryBrokerType: sqs
