forwarder:
  class_name: spellbook_serve.inference.forwarding.forwarding.LoadStreamingForwarder
  args:
    user_port: 5005
    user_hostname: "localhost"
    predict_route: "/stream"
    healthcheck_route: "/readyz"
    batch_route: null
    spellbook_serve_unwrap: true
    serialize_results_as_string: false
