version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  ci:
    jobs:
      - test_server
      - build_image

jobs:
  test_server:
    docker:
      - image: python:3.8-bookworm
        environment:
          ML_INFRA_DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: circleci/postgres:12.9-postgis-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
    resource_class: small
    parallelism: 1
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install Basic Environment Dependencies
          command: | # install dependencies
            apt-get update
            apt-get -y install curl
            pip install --upgrade pip
            pip install -r requirements-dev.txt
      - python/install-packages:
          pkg-manager: pip
          app-dir: server
      - python/install-packages:
          pkg-manager: pip
          app-dir: server
          pip-dependency-file: requirements-test.txt
      - python/install-packages:
          pkg-manager: pip
          app-dir: server
          pip-dependency-file: requirements_override.txt
      - run:
          name: python3 Version
          command: | # Make sure that the workflow is working
            python3 --version
      - run:
          name: Black Formatting Check # Only validation, without re-formatting
          command: |
            black --check --config .black.toml .
      - run:
          name: Isort Formatting Check # Only validation, without re-formatting
          command: |
            isort . --check-only --verbose
      - run:
          name: Unit Tests
          command: |
            cd server
            pip install -e .
            WORKSPACE=.. pytest
  build_image:
    executor: docker-builder
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build . -f server/Dockerfile -t llm-engine:$CIRCLE_SHA1

executors:
  docker-builder:
    machine:
      image: "ubuntu-2004:202201-02"
    resource_class: large

