version: 2.1
orbs:
  python: circleci/python@2.1.0

jobs:
  build_test:
    docker:
      - image: python:3.11-bookworm
    resource_class: small
    parallelism: 1
    steps:
      - checkout # checkout source code to working directory
      - run:
          name: Install Basic Environment Dependencies
          command: | # install dependencies
            apt-get update
            apt-get -y install curl
            pip install --upgrade pip
            pip install -r requirements-dev.txt
      - run:
          name: python3 Version
          command: | # Make sure that the workflow is working
            python3 --version
      - run:
          name: Black Formatting Check # Only validation, without re-formatting
          command: |
            poetry run black --check --config .black.toml .

workflows:
  build_and_test:
    jobs:
      - build_test
