{{- if .Values.autoscaling.horizontal.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "spellbookServe.fullname" . }}
  labels:
    {{- include "spellbookServe.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "spellbookServe.fullname" . }}
  minReplicas: {{ .Values.autoscaling.horizontal.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.horizontal.maxReplicas }}
  metrics:
    - type: Pods
      pods:
        metric:
          name: request-concurrency-average
        target:
          type: Value
          averageValue: {{ .Values.autoscaling.horizontal.targetConcurrency }}
{{- end }}
