forwarder:
  model:
    class_name: spellbook_serve.inference.forwarding.forwarding.LoadForwarder
    args:
      user_port: 5005
      user_hostname: "localhost"
      use_grpc: false
      predict_route: "/predict"
      healthcheck_route: "/readyz"
      batch_route: null
      spellbook_serve_unwrap: false
      serialize_results_as_string: false
      wrap_response: false