apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modelEngine.cachername" . }}
  labels:
    {{- include "modelEngine.selectorLabels.cacher" . | nindent 4 }}
    {{- include "modelEngine.labels" . | nindent 4 }}
    tags.datadoghq.com/service: {{ include "modelEngine.cachername" . }}
spec:
  replicas: {{ .Values.replicaCount.cacher }}
  selector:
    matchLabels:
      {{- include "modelEngine.selectorLabels.cacher" . | nindent 6 }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/main.logs: |
          [{
            "service": {{ include "modelEngine.cachername" . | quote }},
            "source": "python"
          }]
      labels:
        {{- include "modelEngine.selectorLabels.cacher" . | nindent 8 }}
        {{- include "modelEngine.labels" . | nindent 8 }}
        tags.datadoghq.com/service: {{ include "modelEngine.cachername" . }}
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "launch.cachername" . }}
          image: "{{ .Values.image.gatewayRepository }}:{{ .Values.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/readyz
          command:
            - dumb-init
            - --
            - ddtrace-run
          args:
            - python
            - -m
            - model_engine_server.entrypoints.k8s_cache
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- include "launch.cacherEnv" . | indent 10 }}
          {{- include "launch.volumeMounts" . | indent 10 }}
      serviceAccountName: {{ include "launch.fullname" . }}
      {{- include "launch.volumes" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
