apiVersion: v1
kind: Service
metadata:
  name: {{ include "launch.fullname" . }}
  labels:
    {{- include "launch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "launch.selectorLabels.gateway" . | nindent 4 }}
