{{- if .values.virtualService.enabled -}}
{{- $fullName := include "modelEngine.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "modelEngine.labels" . | nindent 4 }}
  {{- with .values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    - model-engine.{{ $.Values.global.networking.internalDomain }}
  gateways:
    - {{ $.Values.global.networking.internalGateway }}
  http:
    - route:
        - destination:
            host: "{{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local"
            port:
              number: 80
      retries:
        attempts: 3
        retryOn: connect-failure,unavailable,gateway-error
{{- end }}
