{{ if .Values.recommendedHardware }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modelEngine.fullname" . }}-recommended-hardware-config
  labels:
    product: common
    team: infra
data:
  byGpuMemoryGb: |-
{{- range $.Values.recommendedHardware.byGpuMemoryGb }}
    - gpu_memory_le: {{ .gpu_memory_le }}
      cpus: {{ .cpus }}
      gpus: {{ .gpus }}
      memory: {{ .memory }}
      storage: {{ .storage }}
      gpu_type: {{ .gpu_type }}
      nodes_per_worker: {{ .nodes_per_worker }}
{{- end }}
  byModelName: |-
{{- range $.Values.recommendedHardware.byModelName }}
    - name: {{ .name }}
      cpus: {{ .cpus }}
      gpus: {{ .gpus }}
      memory: {{ .memory }}
      storage: {{ .storage }}
      gpu_type: {{ .gpu_type }}
      nodes_per_worker: {{ .nodes_per_worker }}
{{- end }}
{{- end }}
