{{- $serviceAccountName := include "launch.fullname" . }}
{{- $serviceAccountNamespaces := (include "launch.serviceAccountNamespaces" . | fromYaml) }}
{{- $annotations := .Values.serviceAccount.annotations }}
{{- $labels := include "launch.labels" . }}
{{- range $namespace := (index $serviceAccountNamespaces "namespaces") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{- printf " %s" $serviceAccountName }}
  namespace: {{- printf " %s" $namespace }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
