{{- if and (.Values.inferenceServiceAccount) (.Values.inferenceServiceAccount.create) }}
{{- $annotations := .Values.inferenceServiceAccount.annotations }}
{{- $labels := include "modelEngine.labels" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo
  # TODO should equal something in serviceTemplateConfigMap
  namespace: (.Values.config.values.launch.endpoint_namespace)
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}