{{- if and (.Values.serviceTemplate) (.Values.serviceTemplate.createServiceAccount) (.Values.serviceTemplate.serviceAccountAnnotations) (.Values.serviceTemplate.serviceAccountName) (.Values.config.values.launch.endpoint_namespace)}}
{{- $annotations := .Values.serviceTemplate.serviceAccountAnnotations }}
# TODO .Values.serviceTemplate.serviceAccountName exists, use that or something similar
{{- $labels := include "modelEngine.labels" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: (.Values.serviceTemplate.serviceAccountName)
  # TODO should equal something in serviceTemplateConfigMap service_template_service_account_name or launch_name
  namespace: (.Values.config.values.launch.endpoint_namespace)
  labels:
    {{- $labels | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}