apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spellbookServe.buildername" . }}
  labels:
    {{- include "spellbookServe.selectorLabels.builder" . | nindent 4 }}
    {{- include "spellbookServe.labels" . | nindent 4 }}
    tags.datadoghq.com/service: {{ include "spellbookServe.buildername" . }}
spec:
  replicas: {{ .Values.replicaCount.builder }}
  selector:
    matchLabels:
      {{- include "spellbookServe.selectorLabels.builder" . | nindent 6 }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        ad.datadoghq.com/main.logs: |
          [{
            "service": {{ include "spellbookServe.buildername" . | quote }},
            "source": "python"
          }]
      labels:
        {{- include "spellbookServe.selectorLabels.builder" . | nindent 8 }}
        {{- include "spellbookServe.labels" . | nindent 8 }}
        tags.datadoghq.com/service: {{ include "spellbookServe.buildername" . }}
        sidecar.istio.io/inject: "false"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "spellbookServe.buildername" . }}
          image: "{{ .Values.image.builderRepository }}:{{ .Values.tag}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/readyz
          command:
            - dumb-init
            - --
            - ddtrace-run
          args:
            - celery
            - --app=spellbook_serve.service_builder
            - worker
            - --loglevel=INFO
            - --concurrency=2
            {{- if .Values.serviceIdentifier }}
            - --queues=spellbook-serve-{{ .Values.serviceIdentifier }}.service-builder
            {{- else }}
            - --queues=spellbook-serve.service-builder
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- include "spellbookServe.builderEnv" . | indent 10 }}
          {{- include "spellbookServe.volumeMounts" . | indent 10 }}
      serviceAccountName: {{ include "spellbookServe.fullname" . }}
      {{- include "spellbookServe.volumes" . | indent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
