dd_trace_enabled: true
spellbook:
  enabled: false
redis:
  auth:
db:
  runDbInitScript: false
  runDbMigrationScript: false
balloonNodeSelector:
  node-lifecycle: normal
nodeSelector:
  node-lifecycle: normal
