dd_trace_enabled: true
spellbook:
  enabled: false
redis:
  auth:
  enableTLS: false
  enableAuth: false
  kedaSecretName: ""
  unsafeSsl: false
db:
  runDbInitScript: false
  runDbMigrationScript: false
balloonNodeSelector:
  node-lifecycle: normal
nodeSelector:
  node-lifecycle: normal
